=== pzoio/impala/tags/1.0-RC3/impala/impala-core/src/org/impalaframework/module/source/moduledefinition.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xsd:schema xmlns="http://www.impalaframework.org/schema/moduledefinition"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.impalaframework.org/schema/moduledefinition"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" />

	<xsd:element name="root">
		<xsd:annotation>
			<xsd:documentation>
				The root element of the module definition file.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence minOccurs="1">
				<xsd:element ref="names" minOccurs="0" />
				<xsd:group ref="moduleGroup"/>
				<xsd:element ref="siblings" minOccurs="0" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="names" type="xsd:string">
		<xsd:annotation>
			<xsd:documentation>
				The names of the module. This element is only used
				when modules are internally describing, that is, when each module
				contains a 'module.properties' file which defines the structure and
				contents of the modules. With internally described modules, this is the only
				element which is really required, but further elements can be added to override the
				structure and definitions contained within the 'module.properties'.
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	
	<xsd:element name="name" type="xsd:string">
		<xsd:annotation>
			<xsd:documentation>
				The name of the module. If within the 'root' element, then refers to the root module.
				Otherwise, refers to the named module.
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	
	<xsd:element name="type" type="xsd:string">
		<xsd:annotation>
			<xsd:documentation>
				The type of the module. By default, is assumed to be 'APPLICATION'.
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:element name="config-locations">
		<xsd:annotation>
			<xsd:documentation>
				A container for 'config-location' elements.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="config-location" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="config-location" type="xsd:string">
		<xsd:annotation>
			<xsd:documentation>
				A module config location. For Spring modules, typically refers to a Spring XML configuration file path.
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:element name="attributes">
		<xsd:annotation>
			<xsd:documentation>
				A container for 'attribute' elements.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="attribute" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="attribute">
		<xsd:annotation>
			<xsd:documentation>
				Used to define arbitrary attribute attached to modules.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="name" type="xsd:string" use="required" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="depends-on" type="xsd:string">
		<xsd:annotation>
			<xsd:documentation>
				A comma separated list of modules on which the current module depends.
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:element name="runtime" type="xsd:string">
		<xsd:annotation>
			<xsd:documentation>
				The module runtime. Is 'spring' by default.
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:element name="modules" type="modulesType">
		<xsd:annotation>
			<xsd:documentation>
				Used to identify child modules of the current module.
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:element name="module">
		<xsd:annotation>
			<xsd:documentation>
				The container for a single module definition. Used for all modules apart from the 'root' modules.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence minOccurs="1">
				<xsd:group ref="moduleGroup"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="siblings" type="modulesType">
		<xsd:annotation>
			<xsd:documentation>
				Used to contain definitions for modules which are not the root module, but are not children of the root module either. 
				Typically, these will be referred to using the 'depends-on' attribute.
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	
	<xsd:group name="moduleGroup">
		<xsd:sequence>
			<xsd:element ref="name" minOccurs="0" />
			<xsd:element ref="type" minOccurs="0" />
			<xsd:element ref="config-locations" minOccurs="0" />
			<xsd:element ref="attributes" minOccurs="0" />
			<xsd:element ref="depends-on" minOccurs="0" />
			<xsd:element ref="runtime" minOccurs="0" />
			<xsd:element ref="modules" minOccurs="0" />
		</xsd:sequence>
	</xsd:group>
	
	<xsd:complexType name="modulesType">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="module" />
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== pzoio/impala/tags/1.0.2/impala/impala-core/resources/xmlinternal/moduledefinition-complete.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="http://www.impalaframework.org/schema/moduledefinition"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.impalaframework.org/schema/moduledefinition http://impala.googlecode.com/svn/schema/moduledefinition.xsd">
    <names>project1</names>
    <name>project1</name>
    <config-locations>
        <config-location>location1</config-location>
        <config-location>location2</config-location>
    </config-locations>
    <attributes>
        <attribute name="prop1">value1</attribute>
        <attribute name="prop2">value2</attribute>
    </attributes>
    <depends-on>module1,module2, module3 , module4 module5</depends-on>
    <runtime>myruntime</runtime>
    <modules>
        <module>
            <name>sample-module2</name>
            <attributes><attribute name = "someatt">value</attribute></attributes>
            <modules>
                <module>
                    <name>sample-module3</name>
                    <config-locations>
                        <config-location>location1</config-location>
                        <config-location>location2</config-location>
                    </config-locations>
                    <attributes>
                        <attribute name="prop1">value1</attribute>
                        <attribute name="prop2">value2</attribute>
                    </attributes>
                    <depends-on>module1,module2, module3 , module4 module5</depends-on>
                    <runtime>myruntime</runtime>
                </module>
            </modules>
        </module>
    </modules>
    <siblings>
        <module>
            <name>sample-module5</name>
            <modules>
                <module>
                    <name>sample-module6</name>
                    <depends-on>sample-module3,sample-module4,sample-module5
                    </depends-on>
                </module>
            </modules>
        </module>
    </siblings>
</root>

=== pzoio/impala/tags/1.0.2/example-sample/example-host/resources/moduledefinitions.xml
<root xmlns="http://www.impalaframework.org/schema/moduledefinition"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation=
      	"http://www.impalaframework.org/schema/moduledefinition http://impala.googlecode.com/svn/schema/moduledefinition.xsd">
    <names>
    example-hibernate
    example-dao
    example-optional
    example-service
    example-web
    example-servlet1
    example-servlet2
    example-servlet3
    example-servlet4
    </names>
    <modules>  
        <module>
            <name>example-dao</name>
            <type>application</type>
            <config-locations>
                <config-location>example-dao-context.xml</config-location>
            </config-locations>
        </module>  
        <module>
            <name>example-web</name>
            <config-locations>
                <config-location>example-web.xml</config-location>
            </config-locations>
        </module>
        <module>
            <name>example-servlet1</name>
            <config-locations>
                <config-location>example-servlet1-context.xml</config-location>
            </config-locations>
        </module>
        <module>
            <name>example-servlet2</name>
            <config-locations>
                <config-location>example-servlet2-context.xml</config-location>
            </config-locations>
        </module>
        <module>
            <name>example-servlet3</name>
            <config-locations>
                <config-location>example-servlet3-context.xml</config-location>
            </config-locations>
        </module>
    </modules>
</root>
