=== pzoio/impala/impala/impala-core/src/org/impalaframework/module/source/moduledefinition.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xsd:schema xmlns="http://www.impalaframework.org/schema/moduledefinition"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.impalaframework.org/schema/moduledefinition"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" />

	<xsd:element name="root">
		<xsd:complexType>
			<xsd:sequence minOccurs="1">
				<xsd:element ref="name" minOccurs="0" />
				<xsd:element ref="config-locations" minOccurs="0" />
				<xsd:element ref="attributes" minOccurs="0" />
				<xsd:element ref="depends-on" minOccurs="0" />
				<xsd:element ref="runtime" minOccurs="0" />
				<xsd:element ref="modules" minOccurs="0" />
				<xsd:element ref="siblings" minOccurs="0" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="name">
	</xsd:element>

	<xsd:element name="config-locations">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="config-location"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="config-location">
	</xsd:element>
	
	<xsd:element name="attributes">		
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="attribute"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="attribute">
	</xsd:element>
	
	<xsd:element name="depends-on">
	</xsd:element>
	
	<xsd:element name="runtime">
	</xsd:element>
	
	<xsd:element name="modules" type="modulesType">
	</xsd:element>
	
	<xsd:element name="module">		
		<xsd:complexType>
			<xsd:sequence minOccurs="1">
				<xsd:element ref="name" minOccurs="0" />
				<xsd:element ref="config-locations" minOccurs="0" />
				<xsd:element ref="attributes" minOccurs="0" />
				<xsd:element ref="depends-on" minOccurs="0" />
				<xsd:element ref="runtime" minOccurs="0" />
				<xsd:element ref="modules" minOccurs="0" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="siblings" type="modulesType">
	</xsd:element>

	<xsd:complexType name="modulesType">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="module" />
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== pzoio/impala/impala/impala-core/resources/xmlinternal/moduledefinition-complete.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="http://www.impalaframework.org/schema/moduledefinition"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.impalaframework.org/schema/moduledefinition http://impala.googlecode.com/svn/schema/moduledefinition.xsd">
	<names>project1</names>
	<name>project1</name>
	<config-locations>
		<config-location>location1</config-location>
		<config-location>location2</config-location>
	</config-locations>
	<attributes>
		<attribute name="prop1">value1</attribute>
		<attribute name="prop2">value2</attribute>
	</attributes>
	<depends-on>module1,module2, module3 , module4 module5</depends-on>
	<runtime>myruntime</runtime>
	<modules>
		<module>
			<name>sample-module2</name>
			<modules>
				<module>
					<name>sample-module3</name>
					<config-locations>
						<config-location>location1</config-location>
						<config-location>location2</config-location>
					</config-locations>
					<attributes>
						<attribute name="prop1">value1</attribute>
						<attribute name="prop2">value2</attribute>
					</attributes>
					<depends-on>module1,module2, module3 , module4 module5</depends-on>
					<runtime>myruntime</runtime>
				</module>
			</modules>
		</module>
	</modules>
	<siblings>
		<module>
			<name>sample-module5</name>
			<modules>
				<module>
					<name>sample-module6</name>
					<depends-on>sample-module3,sample-module4,sample-module5
					</depends-on>
				</module>
			</modules>
		</module>
	</siblings>
</root>
